# Generated by Django 5.2.3 on 2025-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carLogo', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
